# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

disableStartupPopups: true
promptToReturnFromSubprocess: false
notARepository: skip

gui:
  border: single

  theme:
    activeBorderColor:
      - "#31748f"
      - bold

    inactiveBorderColor:
      - "#6e6a86"

    searchingActiveBorderColor:
      - "#ebbcba"
      - bold

    optionsTextColor:
      - "#9ccfd8"

    selectedLineBgColor:
      - "#403d52"

    inactiveViewSelectedLineBgColor:
      - "#21202e"
      - bold

    cherryPickedCommitFgColor:
      - "#1f1d2e"

    cherryPickedCommitBgColor:
      - "#ebbcba"

    markedBaseCommitFgColor:
      - "#9ccfd8"

    markedBaseCommitBgColor:
      - "#f6c177"

    unstagedChangesColor:
      - "#eb6f92"

    defaultFgColor:
      - "#e0def4"

  authorColors:
    "*": "#9ccfd8"
